### ISSUE TITLE
make peers discoverable through libp2p

### ISSUE THREAD

**Issue by inosms** [inosms/magic-recall#3]
### Subtasks
- [ ] create basic libp2p peer discovery functionality
- [ ] create default public server
- [ ] make it possible to discover peers behind NATs

**Comment by inosms** [comment]
:memo: 
for clients: https://github.com/libp2p/rust-libp2p/blob/master/protocols/dcutr/examples/dcutr.rs
for relays: https://github.com/libp2p/rust-libp2p/blob/master/protocols/relay/examples/relay.rs
